version: '3.8'

services:
  db:
    image: postgres:15
    container_name: movie_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gosql
      POSTGRES_DB: movie_db
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_crud_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  pgdata:
