version: '3.8'

services:
  db:
    image: postgres:15
    container_name: movie_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: golang:1.22
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "go install github.com/pressly/goose/v3/cmd/goose@latest &&
       goose -dir ./internal/migrations postgres
       \"host=db user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} sslmode=disable\" up"

  app:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  pgdata:
